### PR TITLE
Feature/add xs searchmultiselect

### PR DESCRIPTION
**Pull request by garrettbear**
https://github.com/gumgum/gumdrops/issues/5

### CODE REVIEW

**Comment by garrettbear** [comment]
Oh 💩 I forgot to update the test. Will do that right now

**Comment by jscottsmith** [comment]
@garrettbear can you look into fixing the context/size select knob options? I think we just need to update storybook. See this issue:

https://github.com/storybooks/storybook/issues/4560

screen shot 2019-02-07 at 11 56 22 am

**Comment by garrettbear** [comment]
I'm on it

**Comment by garrettbear** [comment]
Noticed that the checkboxes in the drop-down menu need to be smaller as well, so adding that as well.

**Comment by garrettbear** [comment]
For fix please see: https://github.com/gumgum/gumdrops/pull/70

**Pull request closed without merging**
