### PR TITLE
Update and prune dependencies to fix warnings

### PR DESCRIPTION
**Pull request by jscottsmith**
Updated Babel and Storybook to latest. Removed some unused/duplicate dependencies.

Addresses #17 and #15

## Changes

- remove `babel` (deprecated for `babel-cli`),
- remove unused `babel-loader`
- remove dupe/beta `@babel/preset-env`
- update Babel related deps to latest
- update Storybook related deps to latest
- add `.prettierignore` and ignore `package.json`
- remove `raw-loader` for md files (built in support in storybook v3.3.0)
- use selectV2, re-order key/values

### CODE REVIEW

**Comment by mnicole** [comment]
for the latest version of storybook, you need to remove a file loader (see my commit here) https://github.com/gumgum/gumdrops/pull/15/files

unless you want to merge both PRs? there is some duplication, so i'm cool with you doing it here or keeping both. if you do keep everything here, can you also please remove @sambego/storybook-state?  thanks!

**Comment by edrpls** [comment]
Sorry for the late review, I'm seeing some warnings, are they expected?
screenshot_20180614_115929

**Comment by jscottsmith** [comment]
Oh, I bumped the version again recently so those probably appeared then. I'll look into them today.

**Comment by jscottsmith** [comment]
Updated. Warnings should be resolved now.

**Pull request merged**
