### PR TITLE
Feature/netlify branch builds

### PR DESCRIPTION
**Pull request by jscottsmith**
This removes Surge.sh build and deployments.
Everything should be handled by Netlify now.
https://www.netlify.com/
Sign up and grant access to your GitHub account to see the admin panel.

### CODE REVIEW

**Comment by edrpls** [comment]
Should I be able to see gumdrops after logging into netlify with github? If that's the case, it's not happening. It gives me the option to add the project, but I would have to set up the deploy settings, which I suppose you already set?

**Comment by jscottsmith** [comment]
@edrpls gahhh! I was looking into adding you to the site deploy I setup -- I think they limit collaborators on the free accounts 😓

I'm setup as administrator which I can transfer ownership too another account, but I'm not sure if we'll be able to share access on the free tier.

screen shot 2019-01-11 at 12 11 22 pm

**Comment by jscottsmith** [comment]
I guess it isn't a big deal because deploys should happen automatically for everything we need. 

Can you can see the build progress or status? 

https://app.netlify.com/sites/gumdrops/deploys/5c38e31ceb15ca00086850e6

**Comment by jscottsmith** [comment]
We could also create a GumDrops Github user that we transfer ownership to and share the account info 😎

**Comment by edrpls** [comment]
Either way sounds good to me, just wanted to verify. Thanks and good job!
:+1:

**Comment by garrettbear** [comment]
I like this update! (**Approved**)

**Pull request merged**
