### PR TITLE
Feature/32 logo login page optional

### PR DESCRIPTION
**Pull request by mnicole**
This PR adds the ability for the GumGum logo to be optional on the login page, in case anyone besides us wants to use it.

And I also updated the git workflow page to not say "stage".

### CODE REVIEW

**Comment by mnicole** [comment]
i was originally going to do that but the image is set through css, so i could manually add an img element perhaps. what do you think?

**Comment by edrpls** [comment]
Maybe it could use a style prop on the element that gets the logo? Something like:

```
const customStyle = props.logoURL ? {background: `url(${props.logoURL})`} : {};
// On the logo element
<div style={customStyle} />
```

This is oversimplified, but do you think it could work?

**Comment by mnicole** [comment]
the custom style won't work because if you set it on the div, you need to know the height and width, which i could also add props for, but that seems like a lot. what do you think?

so i think the only way would be to insert an image tag, but the user would have to make sure it's the right size.

**Comment by edrpls** [comment]
I see, I think it is worth the effort to explore it, but definitely on a different PR, I guess for the time being, people can just add their logos on top of this component.

**Pull request closed without merging**
