### PR TITLE
Feature/jest snapshot tests

### PR DESCRIPTION
**Pull request by jscottsmith**
This adds Jest snapshot testing for most all Gumdrops. I've skipped a few of the really basic ones, where prop configuration is non existent or minimal or tested in other parent components. Also added Enzyme so we can write some UI tests going forward 🙌 

I've also added Travis CI to run tests. This will run builds and tests, if either fail it will display a failed check on the PR.

## Changes
 - Adds and configures Jest and Enzyme for snapshot testing
 - Adds `_tests/jestSetup.js` for configuration
 - Adds new npm scripts, `test` and `test:watch`
 - Adds `_tests` with `atoms`, `layout` and `molecules` directories for test files
 - Adds `test` environment to the babel config
 - Adds `.travis.yml` and configured to run the test script on all branches
 - Added the build status badge (for master branch) to the README 
 - and... Lots of snapshots 📷

### CODE REVIEW

**Comment by jscottsmith** [comment]
Ya good idea, I can update our publish script to run tests before, and I'll add a section to contributing on testing.

**Comment by edrpls** [comment]
The warning doesn't really affect anything, so :man_shrugging:

**Comment by jscottsmith** [comment]
I'll look into resolving the warning.

I just updated the `build.js` to run tests if you can look that over and make sure it's good. @mnicole @edrpls

**Comment by mnicole** [comment]
looks good to me!

**Pull request merged**
